#!/usr/bin/env bash
# Install nginx on your web-01 server that listen on port 80
# A GET query to '/' must return a page that contains "Holberton School"

apt-get update
apt-get install -y nginx

# Create default page
echo "Holberton School" > /var/www/html/index.html

# Configurate server
printf %s "server {
        listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
