#!/usr/bin/env bash
# Recdirect 404 error to a custom file whit the string Ceci n'est pas une page.

apt-get update
apt-get install -y nginx

# Create default page
echo "Holberton School" > /var/www/html/index.html

# Configurate server
ufw allow 'Nginx HTTP'

f_config="/etc/nginx/sites-available/default"
# Add redirection
new_site="https://github.com/EstephaniaCalvoC/"
sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_site permanent;" $f_config

# Add 404 redirection
echo "Ceci n'est pas une page" > /usr/share/nginx/html/my_404.html
new_404="my_404.html"
l_new_404="/my_404.html {root /usr/share/nginx/html;\n internal;}"
sed -i "/listen 80 default_server/a error_page 404 /$new_404; location = $l_new_404" $f_config

service nginx restart
