#!/usr/bin/env bash
#Display Holberton School 10 times and at 9th line print Hi.

i=0

while [ $i -lt 10 ]
do
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    echo "Holberton School"
    (( i++ ))
done
