#!/usr/bin/env bash
#Display bath look, good luck at the 4th and 8th lines respectively
#Display Holberton School at the other lines.

i=1

while [ $i -lt 11 ]
do
    if [ $i -eq 4 ]
    then
	echo "bad luck"
    elif [ $i -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    (( i++ ))
done
