#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
#   Display "bad luck from China" for the 4th line
#   Display "bad luck from Japan" for the 9th line
#   Display "bad luck from Italy" for the 17th line

i=1

while [ $i -le 20 ]
do
    echo "$i"
    case $i in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
    esac
    (( i++ ))
done
