#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic
# except the following TCP ports:
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)

apt-get -y update
apt-get -y install ufw

ufw disable
ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp

ufw enable
